# Generated by Django 6.0.6 on 2026-06-18 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_football_id', models.IntegerField(unique=True)),
                ('league', models.CharField(choices=[('EPL', 'English Premier League'), ('LA_LIGA', 'La Liga'), ('SERIE_A', 'Serie A'), ('BUNDESLIGA', 'Bundesliga'), ('LIGUE_1', 'Ligue 1')], max_length=20)),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('home_team_logo', models.URLField(blank=True, null=True)),
                ('away_team_logo', models.URLField(blank=True, null=True)),
                ('kickoff_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('finished', 'Finished'), ('postponed', 'Postponed')], default='scheduled', max_length=15)),
                ('minute', models.IntegerField(blank=True, null=True)),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
                ('live_stats', models.JSONField(blank=True, null=True)),
                ('winnie_prediction', models.JSONField(blank=True, null=True)),
                ('prediction_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['kickoff_time'],
            },
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('goal', 'Goal'), ('yellow_card', 'Yellow Card'), ('red_card', 'Red Card'), ('substitution', 'Substitution'), ('var', 'VAR Decision')], max_length=20)),
                ('team', models.CharField(max_length=100)),
                ('player', models.CharField(blank=True, max_length=100)),
                ('minute', models.IntegerField()),
                ('detail', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='matches.match')),
            ],
            options={
                'ordering': ['minute'],
            },
        ),
        migrations.CreateModel(
            name='MatchRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_room', to='chat.conversation')),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='matches.match')),
            ],
        ),
    ]
