# Generated by Django 6.0.6 on 2026-07-03 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueStanding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_id', models.IntegerField()),
                ('league_name', models.CharField(max_length=100)),
                ('season', models.IntegerField()),
                ('team_id', models.IntegerField()),
                ('team_name', models.CharField(max_length=100)),
                ('team_logo', models.URLField(blank=True, null=True)),
                ('rank', models.IntegerField()),
                ('points', models.IntegerField()),
                ('goals_diff', models.IntegerField()),
                ('form', models.CharField(blank=True, max_length=10)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('played', models.IntegerField()),
                ('win', models.IntegerField()),
                ('draw', models.IntegerField()),
                ('lose', models.IntegerField()),
                ('goals_for', models.IntegerField()),
                ('goals_against', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['league_id', 'rank'],
                'unique_together': {('league_id', 'season', 'team_id')},
            },
        ),
    ]
