# Generated by Django 6.0.6 on 2026-07-04 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_player'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeagueStanding',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
