# Generated by Django 6.0.6 on 2026-07-10 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_playermatchstat'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchOdds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmaker_name', models.CharField(blank=True, max_length=100)),
                ('data', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='odds', to='matches.match')),
            ],
        ),
    ]
