# Generated by Django 6.0.6 on 2026-07-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_matchlineup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchevent',
            name='event_type',
            field=models.CharField(choices=[('goal', 'Goal'), ('yellow_card', 'Yellow Card'), ('red_card', 'Red Card'), ('substitution', 'Substitution'), ('var', 'VAR Decision'), ('other', 'Other')], max_length=20),
        ),
    ]
