# Generated by Django 6.0.6 on 2026-07-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0009_alter_matchevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchevent',
            name='assist_player',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
