# Generated by Django 6.0.6 on 2026-07-22 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0010_matchevent_assist_player'),
        ('teams', '0002_backfill_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='away_team_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='teams.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='teams.team'),
        ),
        migrations.AddField(
            model_name='matchevent',
            name='team_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='teams.team'),
        ),
        migrations.AddField(
            model_name='playermatchstat',
            name='team_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='teams.team'),
        ),
    ]
