# Generated by Django 6.0.6 on 2026-07-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('api_football_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('founded', models.IntegerField(blank=True, null=True)),
                ('national', models.BooleanField(default=False)),
                ('logo', models.URLField(blank=True, null=True)),
                ('venue_name', models.CharField(blank=True, max_length=150, null=True)),
                ('venue_city', models.CharField(blank=True, max_length=100, null=True)),
                ('venue_capacity', models.IntegerField(blank=True, null=True)),
                ('transfermarkt_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('squad_value_eur', models.BigIntegerField(blank=True, null=True)),
                ('transfer_balance_eur', models.BigIntegerField(blank=True, null=True)),
                ('match_confidence', models.FloatField(blank=True, null=True)),
                ('tm_synced_at', models.DateTimeField(blank=True, null=True)),
                ('tm_raw', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
