# Generated by Django 6.0.6 on 2026-07-22 08:15

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_backfill_teams'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='team',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='team_name_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
