# Generated by Django 6.0.6 on 2026-07-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_team_name_trgm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='transfer_balance_eur',
        ),
        migrations.AddField(
            model_name='team',
            name='squad_acquisition_value_eur',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
