# Generated by Django 6.0.6 on 2026-07-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_remove_team_transfer_balance_eur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransfermarktClub',
            fields=[
                ('transfermarkt_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('logo', models.URLField(blank=True, null=True)),
                ('country_id', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
