# Generated by Django 6.0.6 on 2026-07-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_favorite_league_user_favorite_team_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banner',
            field=models.URLField(blank=True, null=True),
        ),
    ]
