# Generated by Django 6.0.6 on 2026-07-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_team_logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
