# Generated by Django 6.0.6 on 2026-07-22 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_backfill_teams'),
        ('users', '0006_user_favorite_team_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_team_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='teams.team'),
        ),
    ]
