# Generated by Django 6.0.6 on 2026-07-13 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_membership_last_read_at_messagepollvote'),
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitypost',
            name='post_type',
            field=models.CharField(choices=[('text', 'Text'), ('match_object', 'Match Object'), ('poll', 'Poll'), ('winnie_insight', 'Winnie Insight')], default='text', max_length=20),
        ),
        migrations.CreateModel(
            name='CommunityRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='communities.community')),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='community_room', to='chat.conversation')),
            ],
        ),
    ]
