# Generated by Django 6.0.6 on 2026-07-11 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
        ('matches', '0010_matchevent_assist_player'),
    ]

    operations = [
        # Clear the composite unique constraint BEFORE removing the fields it
        # references (autodetector emitted these in the wrong order).
        migrations.AlterUniqueTogether(
            name='pollvote',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='polloption',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='pollvote',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='pollvote',
            name='option',
        ),
        migrations.RemoveField(
            model_name='pollvote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='match_id',
        ),
        migrations.AddField(
            model_name='post',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_posts', to='matches.match'),
        ),
        migrations.AddField(
            model_name='post',
            name='media_state',
            field=models.CharField(choices=[('ready', 'Ready'), ('processing', 'Processing')], default='ready', max_length=12),
        ),
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video')], max_length=10)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='ready', max_length=12)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('url', models.URLField(blank=True, max_length=800, null=True)),
                ('storage_key', models.CharField(blank=True, max_length=500, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('mux_upload_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('mux_asset_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('mux_playback_id', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=800, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='feed.post')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Poll',
        ),
        migrations.DeleteModel(
            name='PollOption',
        ),
        migrations.DeleteModel(
            name='PollVote',
        ),
    ]
