# Generated by Django 6.0.6 on 2026-07-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerLeagueStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_id', models.IntegerField()),
                ('season', models.IntegerField()),
                ('player_id', models.IntegerField()),
                ('player_name', models.CharField(max_length=150)),
                ('player_photo', models.URLField(blank=True, null=True)),
                ('team_id', models.IntegerField()),
                ('team_name', models.CharField(max_length=100)),
                ('team_logo', models.URLField(blank=True, null=True)),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('appearances', models.IntegerField(default=0)),
                ('rank_type', models.CharField(max_length=20)),
                ('rank_position', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['rank_type', 'rank_position'],
                'unique_together': {('league_id', 'season', 'player_id', 'rank_type')},
            },
        ),
    ]
