# Generated by Django 6.0.6 on 2026-07-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_playerleaguestat'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_id', models.IntegerField()),
                ('team_id', models.IntegerField()),
                ('season', models.IntegerField()),
                ('team_name', models.CharField(max_length=100)),
                ('team_logo', models.URLField(blank=True, null=True)),
                ('form', models.CharField(blank=True, max_length=100)),
                ('data', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('league_id', 'team_id', 'season')},
            },
        ),
    ]
