# Generated by Django 6.0.6 on 2026-07-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_teamstatistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=150)),
                ('league_type', models.CharField(blank=True, max_length=30, null=True)),
                ('logo', models.URLField(blank=True, null=True)),
                ('country_name', models.CharField(blank=True, max_length=100, null=True)),
                ('country_code', models.CharField(blank=True, max_length=10, null=True)),
                ('country_flag', models.URLField(blank=True, null=True)),
                ('current_season', models.IntegerField(blank=True, null=True)),
                ('is_core_league', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['country_name', 'name'],
            },
        ),
    ]
