# Generated by Django 6.0.6 on 2026-07-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0004_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
