# Generated by Django 6.0.6 on 2026-07-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0006_userleaguefollow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguestanding',
            name='form',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
