# Generated by Django 6.0.6 on 2026-07-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0007_alter_leaguestanding_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerleaguestat',
            name='full_stats',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
