# Generated by Django 6.0.6 on 2026-07-07 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0008_playerleaguestat_full_stats'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueTeamSyncStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_id', models.IntegerField()),
                ('season', models.IntegerField()),
                ('team_id', models.IntegerField()),
                ('team_name', models.CharField(blank=True, max_length=100)),
                ('players_synced', models.BooleanField(default=False)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('league_id', 'season', 'team_id')},
            },
        ),
    ]
