# Generated by Django 6.0.6 on 2026-07-22 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0010_userteamfollow'),
        ('teams', '0002_backfill_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguestanding',
            name='team_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='teams.team'),
        ),
        migrations.AddField(
            model_name='leagueteamsyncstatus',
            name='team_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='teams.team'),
        ),
        migrations.AddField(
            model_name='playerleaguestat',
            name='team_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='teams.team'),
        ),
        migrations.AddField(
            model_name='teamstatistics',
            name='team_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='teams.team'),
        ),
        migrations.AddField(
            model_name='userteamfollow',
            name='team_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='teams.team'),
        ),
    ]
