# Generated by Django 6.0.6 on 2026-07-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0013_drop_denormalized_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='transfermarkt_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
