# Generated by Django 6.0.6 on 2026-07-22 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_country'),
        ('teams', '0002_backfill_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='team_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='teams.team'),
        ),
    ]
