from django.db import migrations


class Migration(migrations.Migration):
    """Phase 5: drop the denormalized team_id/team_name from Player and rename the
    Phase-3 FK team_ref -> team. Hand-written (not autogenerated) so the rename is
    an explicit RenameField and Django can't misread it as drop+recreate, which
    would lose the FK data. Order matters: the int `team_id` column is dropped
    first so the FK's column can be renamed team_ref_id -> team_id without
    colliding."""

    dependencies = [
        ('players', '0004_backfill_team_fk'),
    ]

    operations = [
        migrations.RemoveField(model_name='player', name='team_id'),
        migrations.RemoveField(model_name='player', name='team_name'),
        migrations.RenameField(model_name='player', old_name='team_ref', new_name='team'),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['team', 'position', 'number']},
        ),
    ]
