# Generated by Django 6.0.6 on 2026-07-22 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_drop_denormalized_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='agent',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='contract_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='market_value_eur',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='match_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='preferred_foot',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='previous_value_eur',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tm_raw',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='tm_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='transfermarkt_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='PlayerTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tm_transfer_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('from_tm_club_id', models.IntegerField(blank=True, null=True)),
                ('to_tm_club_id', models.IntegerField(blank=True, null=True)),
                ('fee_eur', models.BigIntegerField(blank=True, null=True)),
                ('market_value_eur', models.BigIntegerField(blank=True, null=True)),
                ('transfer_type', models.CharField(blank=True, max_length=30, null=True)),
                ('season_id', models.IntegerField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='players.player')),
            ],
            options={
                'ordering': ['player', '-date'],
            },
        ),
        migrations.CreateModel(
            name='PlayerMarketValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value_eur', models.BigIntegerField()),
                ('tm_club_id', models.IntegerField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('season_id', models.IntegerField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_value_history', to='players.player')),
            ],
            options={
                'ordering': ['player', 'date'],
                'unique_together': {('player', 'date')},
            },
        ),
    ]
