# Generated by Django 6.0.6 on 2026-07-11 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('kickoff', 'Kickoff Reminder'), ('goal', 'Goal Alert'), ('card', 'Card'), ('substitution', 'Substitution'), ('reply', 'Reply'), ('repost', 'Repost'), ('follow', 'New Follower'), ('reaction', 'Reaction'), ('winnie_alert', 'Winnie Alert'), ('community_post', 'Community Post'), ('match_result', 'Match Result'), ('mention', 'Mention')], max_length=20),
        ),
        migrations.CreateModel(
            name='ExpoPushToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('device_type', models.CharField(blank=True, choices=[('android', 'Android'), ('ios', 'iOS')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expo_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
